const industries = [
    "Analytics",
    "Business",
    "Accounting",
    "Video blogging",
    "Design",
    "Investments",
    "Engineering",
    "Foreign languages",
    "Art",
    "Cybersecurity",
    "Crowdfunding",
    "Cryptocurrency",
    "Medicine",
    "Music",
    "Management",
    "Oil industry",
    "Programming",
    "Psychology",
    "Communications",
    "Agriculture",
    "Media",
    "Sport",
    "Startups",
    "Construction",
    "Trade",
    "Tourism",
    "Economy",
    "Jurisprudence"
];
export default industries